### PR TITLE
Fix missing files

### PR DESCRIPTION
**Pull request by LitoMore**
The v3 fails on https://github.com/simple-icons/simple-icons/actions/runs/8218210353/job/22474817328

Some people may add `node_modules` to their Git global excluded files list. I've added `!node_modules` to the `.gitignore`.

I also used `npm install` command to update the npm lockfile since we bumped Node.js 20.

### CODE REVIEW

**Comment by ericcornelissen** [comment]
Thanks @LitoMore!

I added the `lockfile-version` property to explicitly set the lockfile version for the future and also committed changes after running `npm clean-install` which (somehow) added some more missing files (and changed the manifests in `node_modules/`).

Did you manually test your changes? If so, do you feel like testing the additional changes I made too? If not, I'll merge this as is and create a new release.

**Comment by LitoMore** [comment]
I didn't test it on my local. I got an `::error::Shescape does not support the shell sh` when trying `node index.js`. I didn't read too much code of Shascape. How can I bypass this?

**Comment by ericcornelissen** [comment]
The error you linked above seems unrelated to running the script locally, rather it's related to the GitHub Actions side of things. Hence, I'd test this by trying to use it in a workflow by using it as `kceb/git-message-action@fix-missing-files`, which you could do in a temporary/test repository. Let me know if you want to do that or I should just merge this and release.

> I didn't test it on my local. I got an `::error::Shescape does not support the shell sh` when trying `node index.js`. I didn't read too much code of Shascape. How can I bypass this?

This most likely happens because you're on MacOS, is that correct? It _could_ be overcome by specifying the shell to use when executing the git command (e.g. to `"bash"`), but that might still not work for everyone. Since this isn't intended to run locally I hesitate to "fix" this problem. Another option would be to rewrite this Action as a shell script similar to [`ericcornelissen/git-tag-annotation-action`](https://github.com/ericcornelissen/git-tag-annotation-action).

**Comment by ericcornelissen** [comment]
I tested these changes in a private repository and upgraded `@actions/core` to fix warnings about the set-output functionality.

**Pull request merged**
